language: node_js

node_js:
  - '12'

cache: yarn
  
install:
  - yarn

script:
  - yarn run build

branches:
  only:
    - prod
    - dev

deploy:
  provider: heroku
  app: digimov-frontend
  api_key:
    secure: $HEROKU_API_KEY